name: Test-Automation

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:


jobs:
  build:
    name: Run Test Automation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.1'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest selenium openpyxl
      
      - name: Run tests
        run: |
          pytest -v -s test_login.py
